<?php
    require_once("db/connect.php");
    if(!isset($_GET["id"])){
        header("Location:select_race.php");
    }else{
        $id=$_GET["id"];
        $result=$controller->delete($id);
        if($result){
            header("Location:select_race.php");
        }
    }
?>